apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}
  food: {{ .Values.favorite.food | upper | quote }}
  number: {{ .Values.favorite.number | quote }}
  date: {{ now }}
  required_field: {{ required "A value is required!" .Values.required_field }}
