apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  {{- if eq .drink "coffee" }}
  mug: "true"
  {{- end }}
  food: {{ .food | upper | quote }}
  number: {{ .number | quote }}
  release: {{ $.Release.Name }}
  release_using_var: {{ $relname }}
  {{- end }}
  required_field: {{ required "A value is required!" .Values.required_field }}
  date: {{ now }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . | title | quote }}
    {{- end }}
